plugin: google.cloud.gcp_compute
projects:
  - <project id>
auth_kind: serviceaccount
service_account_file: /home/UserName/ansible-sa.json
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
groups:
  wordpress: "'wp-instance' in name"
